version: '3'

networks:
  my-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendrier_management
    ports:
      - "3307:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  calendrier-service:
    build:
      context: ./CalendrierService
    ports:
      - "8091:8091"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/calendrier_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8091
      SPRING_APPLICATION_NAME: CALENDRIER-SERVICE
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql

  categorie-service:
    build:
      context: ./CategorieService
    ports:
      - "8089:8089"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Categorie_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8089
      SPRING_APPLICATION_NAME: CATEGORIE-SERVICE
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql

  contact-service:
    build:
      context: ./ContactService
    ports:
      - "8086:8086"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Contact_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8086
      SPRING_APPLICATION_NAME: CONTACT-SERVICE
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql

  eureka-server:
    build:
      context: ./Eureka_Server
    ports:
      - "8761:8761"
    networks:
      - my-network

  gateway-service:
    build:
      context: ./GateWay
    ports:
      - "8888:8888"
    networks:
      - my-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  utilisateur-service:
    build:
      context: ./UtilisateurService
    ports:
      - "8093:8093"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/users_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8093
      SPRING_APPLICATION_NAME: SERVICE-USER
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql

volumes:
  mysql-data:
